# Welcome to Jekyll!
#

# Site settings
title: Yashas Joshi
description: |
  Just another undergrad !!!
owner: Yashas Joshi # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: yashasjoshi1996@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/yashasjoshi1996
  github: https://github.com/yashasjoshi
  linkedin-square: https://linkedin.com/in/yashas-joshi-ba4841aa/
  facebook-official: https://facebook.com/yashasjoshi1996
  google-plus-square: https://plus.google.com/+YashasJoshi1996
  #email: /contact/
  instagram: https://www.instagram.com/_im_the_one_who_knocks_/
  youtube-square: https://www.youtube.com/channel/UCkaQETk-K6xwCWep412KQrg
  #spotify:
  #stack-overflow:
  wordpress: https://yashasjoshiblog.wordpress.com/
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/yashas-joshi
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
